{% set version = "1.23.0" %}

package:
  name: google-cloud-storage
  version: {{ version }}

source:
  fn: google-cloud-storage-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/g/google-cloud-storage/google-cloud-storage-{{ version }}.tar.gz
  sha256: c66e876ae9547884fa42566a2ebfec51d280f488d7a058af9611ba90c78bed78

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python >=2.7,<3.0dev|>=3.4,<4.0dev
    - google-auth >=1.2.0,<2.0dev
    - google-cloud-core >=1.0.3,< 2.0dev
    - google-resumable-media >=0.5.0,<0.6dev

test:
  requires:
    - python >=2.7,<3.0dev|>=3.4,<4.0dev
  imports:
    - google
    - google.cloud
    - google.cloud.storage

about:
  home: https://github.com/GoogleCloudPlatform/google-cloud-python
  summary: Python Client for Google Cloud Storage
  doc_url: https://googlecloudplatform.github.io/google-cloud-python/stable/google-cloud-api.html
  dev_url: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/storage
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johanneskoester
    - tswast
    - andreyz4k
