{% set name = "google-cloud-storage" %}
{% set version = "3.0.0" %}

package:
  name: google-cloud-storage
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2accb3e828e584888beff1165e5f3ac61aa9088965eb0165794a82d8c7f95297

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - google-auth >=2.26.1,<3.0dev
    - google-api-core >=2.15.0,<3.0.0dev
    - google-cloud-core >=2.3.0,<3.0dev
    - google-resumable-media >=2.7.2
    - requests >=2.18.0,<3.0.0dev
    - google-crc32c >=1.0,<2.0dev
    # protobuf extra
    - protobuf <6.0.0dev

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - google
    - google.cloud
    - google.cloud.storage
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-storage
  summary: Python Client for Google Cloud Storage
  doc_url: https://googleapis.dev/python/storage/latest/index.html
  dev_url: https://github.com/googleapis/python-storage
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - andreyz4k
    - johanneskoester
    - tswast
