{% set version = "2.3.0" %}

package:
  name: google-cloud-storage
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/google-cloud-storage/google-cloud-storage-{{ version }}.tar.gz
  sha256: f4cbb0de5e17228e9c09cdc897d81eaa70e2c396f58513f79de0e824584c8f5b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - google-auth >=1.25.0,<3.0dev
    - google-api-core >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - google-cloud-core >=2.3.0,<3.0dev
    - google-resumable-media >=2.3.2
    - requests >=2.18.0,<3.0.0dev
    - protobuf

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.cloud
    - google.cloud.storage
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-storage
  summary: Python Client for Google Cloud Storage
  doc_url: https://googleapis.dev/python/storage/latest/index.html
  dev_url: https://github.com/googleapis/python-storage
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - andreyz4k
    - johanneskoester
    - leahecole
    - tswast
