{% set version = "1.27.0" %}

package:
  name: google-cloud-storage
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/google-cloud-storage/google-cloud-storage-{{ version }}.tar.gz
  sha256: 62d5efa529fb39ae01504698b7053f2a009877d0d4b3c8f297e3e68c8c38a117

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python
  run:
    - google-auth >=1.11.0,<2.0dev
    - google-cloud-core >=1.2.0,<2.0dev
    - google-resumable-media >=0.5.0,<0.6dev
    - python

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.cloud
    - google.cloud.storage
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/google-cloud-python
  summary: Python Client for Google Cloud Storage
  doc_url: https://googleapis.dev/python/storage/latest/index.html
  dev_url: https://github.com/googleapis/google-cloud-python/tree/master/storage
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andreyz4k
    - johanneskoester
    - leahecole
    - tswast
