{% set name = "google-cloud-storage" %}
{% set version = "3.2.0" %}

package:
  name: google-cloud-storage
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: decca843076036f45633198c125d1861ffbf47ebf5c0e3b98dcb9b2db155896c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - google-auth >=2.26.1,<3.0.0
    - google-api-core >=2.15.0,<3.0.0
    - google-cloud-core >=2.4.2,<3.0.0
    - google-resumable-media >=2.7.2,<3.0.0
    - requests >=2.22.0,<3.0.0
    - google-crc32c >=1.1.3,<2.0.0
    # protobuf extra
    - protobuf >=3.20.2,<7.0.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - google
    - google.cloud
    - google.cloud.storage
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-storage
  summary: Python Client for Google Cloud Storage
  doc_url: https://googleapis.dev/python/storage/latest/index.html
  dev_url: https://github.com/googleapis/python-storage
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - andreyz4k
    - johanneskoester
    - tswast
