{% set version = "2.1.0" %}

package:
  name: google-cloud-storage
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/google-cloud-storage/google-cloud-storage-{{ version }}.tar.gz
  sha256: 0a5e7ab1a38d2c24be8e566e50b8b0daa8af8fd49d4ab312b1fda5c147429893

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - google-auth >=1.25.0,<3.0dev
    - google-api-core >=1.29.0,<3.0dev
    - google-cloud-core >=1.6.0,<3.0dev
    - google-resumable-media >=1.3.0
    - requests >=2.18.0,<3.0.0dev
    - protobuf

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.cloud
    - google.cloud.storage
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-storage
  summary: Python Client for Google Cloud Storage
  doc_url: https://googleapis.dev/python/storage/latest/index.html
  dev_url: https://github.com/googleapis/python-storage
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - andreyz4k
    - johanneskoester
    - leahecole
    - tswast
