{% set version = "1.37.1" %}

package:
  name: google-cloud-storage
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/google-cloud-storage/google-cloud-storage-{{ version }}.tar.gz
  sha256: e06a4797c87ac73c4a74801539fdf0a91761c3014281ff58b7b29f15b34c206e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - google-auth >=1.11.0,<2.0dev
    - google-cloud-core >=1.4.1,<2.0dev
    - google-resumable-media >=1.2.0,<2.0dev
    - requests >=2.18.0,<3.0.0dev
    # Workaround for https://github.com/conda-forge/aiohttp-feedstock/issues/43
    - yarl <1.6.0,>=1.0

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.cloud
    - google.cloud.storage
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-storage
  summary: Python Client for Google Cloud Storage
  doc_url: https://googleapis.dev/python/storage/latest/index.html
  dev_url: https://github.com/googleapis/python-storage
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andreyz4k
    - johanneskoester
    - leahecole
    - tswast
