{% set version = "1.19.0" %}

package:
  name: google-cloud-storage
  version: {{ version }}

source:
  fn: google-cloud-storage-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/g/google-cloud-storage/google-cloud-storage-{{ version }}.tar.gz
  sha256: 21f94c073eb9be34ca545c4eef28ae66947386687d99cd3a82400bf1504cfbd8

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    - google-auth >=1.2.0
    - google-cloud-core >=1.0.0
    - google-api-core >=1.6.0
    - google-resumable-media >=0.3.1

test:
  requires:
    - python 3.6  # work around temporary protobuf issues
  imports:
    - google
    - google.cloud
    - google.cloud.storage

about:
  home: https://github.com/GoogleCloudPlatform/google-cloud-python
  summary: Python Client for Google Cloud Storage
  doc_url: https://googlecloudplatform.github.io/google-cloud-python/stable/google-cloud-api.html
  dev_url: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/storage
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johanneskoester
    - tswast
    - andreyz4k
