{% set version = "1.15.1" %}

package:
  name: google-cloud-storage
  version: {{ version }}

source:
  fn: google-cloud-storage-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/g/google-cloud-storage/google-cloud-storage-{{ version }}.tar.gz
  sha256: 8032e576e2f91a1d3de2355118040c3bcd9916e0453a6b3f64c1b42ed151690a

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    - google-cloud-core >=0.29.0
    - google-api-core >=1.6.0
    - google-resumable-media >=0.3.1

test:
  requires:
    - python 3.6  # work around temporary protobuf issues
  imports:
    - google
    - google.cloud
    - google.cloud.storage

about:
  home: https://github.com/GoogleCloudPlatform/google-cloud-python
  summary: Python Client for Google Cloud Storage
  doc_url: https://googlecloudplatform.github.io/google-cloud-python/stable/google-cloud-api.html
  dev_url: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/storage
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johanneskoester
    - tswast
    - andreyz4k
