# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 3.5.0
  python_check_max: '3.14'

package:
  name: google-cloud-storage
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/google-cloud-storage/google_cloud_storage-${{ version }}.tar.gz
  sha256: 10b89e1d1693114b3e0ca921bdd28c5418701fd092e39081bb77e5cee0851ab7

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --no-build-isolation

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - google-api-core >=2.27.0,<3.0.0
    - google-auth >=2.26.1,<3.0.0
    - google-cloud-core >=2.4.2,<3.0.0
    - google-crc32c >=1.1.3,<2.0.0
    - google-resumable-media >=2.7.2,<3.0.0
    - requests >=2.22.0,<3.0.0
tests:
  - python:
      imports:
        - google
        - google.cloud
        - google.cloud.storage
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*

about:
  summary: Python Client for Google Cloud Storage
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/googleapis/python-storage
  repository: https://github.com/googleapis/python-storage
  documentation: https://googleapis.dev/python/storage/latest/index.html

extra:
  recipe-maintainers:
    - xylar
    - andreyz4k
    - johanneskoester
    - tswast
